name: Building metis website

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3


      - name: install node and npm
        run: |
            sudo apt update
            sudo apt install nodejs npm
            node --version

      - name: start build script
        run: |
            npm install
            npm run build




      - name: Pushes to the website repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          # SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_GITHUB_TOKEN }}
        with:
          source-directory: 'dist'
          destination-github-username: 'santoshkurmi'
          destination-repository-name: 'website'
          user-email: xantosh121@gmail.com
          target-branch: main

          